spring.application.name=Laboratorio-TAIS

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/laboratorio_db?authSource=admin}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin}